name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
      - run: npm test
        
      - name: Run ESLint
        run: npx eslint Backend --config Backend/.eslintrc.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          application_name: housingservice950
          environment_name: housingservice950-env
