name: Jest CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm install

      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
