name: Python CI
on: [push]
jobs:
 build:
 runs-on: ubuntu-latest
 strategy:
 matrix:
 python-version: [3.7, 3.8, 3.9]
 steps:
 - uses: actions/checkout@v2
 - name: Set up Python ${{ matrix.python-version }}
 uses: actions/setup-python@v2
 with:
 python-version: ${{ matrix.python-version }}
 - name: Install dependencies
 run: |
 python -m pip install --upgrade pip
This sample configuration file defines a workflow called "Python CI" that runs automatically every time code
is pushed. The workflow will run under three different Python versions (3.7, 3.8, 3.9) to ensure code
compatibility in different environments. The configuration file first sets up the Python environment, then
installs the project dependencies, and finally runs the unit tests for the project.
To apply this configuration to your Python project, simply add the file to the '.github/workflows' directory
and GitHub Actions will be performed automatically. Please adjust the configuration file according to your
project requirements.
Example of CI
Here's an example: Suppose you have a simple Python calculator project that contains a calculator.py file
and a test_calculator.py file for unit testing.
 pip install -r requirements.txt
 - name: Run tests
 run: |
 python -m unittest testfile
